//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.CDIndex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Octopus.CDIndex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the &quot;{0}&quot; file information?.
        /// </summary>
        internal static string AreUSureToDeleteFile {
            get {
                return ResourceManager.GetString("AreUSureToDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the &quot;{0}&quot; folder information?.
        /// </summary>
        internal static string AreUSureToDeleteFolder {
            get {
                return ResourceManager.GetString("AreUSureToDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the &quot;{0}&quot; volume information?.
        /// </summary>
        internal static string AreUSureToDeleteVolume {
            get {
                return ResourceManager.GetString("AreUSureToDeleteVolume", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ArrowDownBmp {
            get {
                object obj = ResourceManager.GetObject("ArrowDownBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowUpBmp {
            get {
                object obj = ResourceManager.GetObject("ArrowUpBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AudioHS {
            get {
                object obj = ResourceManager.GetObject("AudioHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Basic.
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap BlueHeader {
            get {
                object obj = ResourceManager.GetObject("BlueHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CD_16 {
            get {
                object obj = ResourceManager.GetObject("CD_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing....
        /// </summary>
        internal static string Closing {
            get {
                return ResourceManager.GetString("Closing", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Collapsed {
            get {
                object obj = ResourceManager.GetObject("Collapsed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Control_TreeView {
            get {
                object obj = ResourceManager.GetObject("Control_TreeView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dbs {
            get {
                object obj = ResourceManager.GetObject("dbs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete Folder....
        /// </summary>
        internal static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete Volume....
        /// </summary>
        internal static string DeleteVolume {
            get {
                return ResourceManager.GetString("DeleteVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IO error occured: {0}.
        /// </summary>
        internal static string ErrorIO {
            get {
                return ResourceManager.GetString("ErrorIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file &quot;{0}&quot;. Error message: {1}.
        /// </summary>
        internal static string ErrorSavingFile {
            get {
                return ResourceManager.GetString("ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Database To.
        /// </summary>
        internal static string ExportDatabaseTo {
            get {
                return ResourceManager.GetString("ExportDatabaseTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octopus Files (*.octopus)|*.octopus|Comma separated values (*.csv)|*.csv.
        /// </summary>
        internal static string ExportFilter {
            get {
                return ResourceManager.GetString("ExportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found in database..
        /// </summary>
        internal static string FileNotFoundInDatabase {
            get {
                return ResourceManager.GetString("FileNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling controls....
        /// </summary>
        internal static string FillingControls {
            get {
                return ResourceManager.GetString("FillingControls", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FindBmp {
            get {
                object obj = ResourceManager.GetObject("FindBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &amp;Properties.
        /// </summary>
        internal static string FolderProperties {
            get {
                return ResourceManager.GetString("FolderProperties", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap gear_1 {
            get {
                object obj = ResourceManager.GetObject("gear_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing components....
        /// </summary>
        internal static string InitializingComponents {
            get {
                return ResourceManager.GetString("InitializingComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date range..
        /// </summary>
        internal static string InvalidDateRange {
            get {
                return ResourceManager.GetString("InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format. Enter a number..
        /// </summary>
        internal static string InvalidNumberFormat {
            get {
                return ResourceManager.GetString("InvalidNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid size range..
        /// </summary>
        internal static string InvalidSizeRange {
            get {
                return ResourceManager.GetString("InvalidSizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Database With.
        /// </summary>
        internal static string MergeDatabaseWith {
            get {
                return ResourceManager.GetString("MergeDatabaseWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octopus Files (*.octopus)|*.octopus.
        /// </summary>
        internal static string MergeFilter {
            get {
                return ResourceManager.GetString("MergeFilter", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap networkConnections {
            get {
                object obj = ResourceManager.GetObject("networkConnections", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files selected..
        /// </summary>
        internal static string NoFiles {
            get {
                return ResourceManager.GetString("NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive {0} looks like a non-removeable media. Indexing process will take a large amount of time. Would you like to continue?.
        /// </summary>
        internal static string NonRemoveableMsg {
            get {
                return ResourceManager.GetString("NonRemoveableMsg", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap openHS {
            get {
                object obj = ResourceManager.GetObject("openHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OptionsHS {
            get {
                object obj = ResourceManager.GetObject("OptionsHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Properties {
            get {
                object obj = ResourceManager.GetObject("Properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading database....
        /// </summary>
        internal static string ReadingDatabase {
            get {
                return ResourceManager.GetString("ReadingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading database... {0}%.
        /// </summary>
        internal static string ReadingDatabasePercent {
            get {
                return ResourceManager.GetString("ReadingDatabasePercent", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving application settings....
        /// </summary>
        internal static string SavingApplicationSettings {
            get {
                return ResourceManager.GetString("SavingApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving database....
        /// </summary>
        internal static string SavingDatabase {
            get {
                return ResourceManager.GetString("SavingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected files.
        /// </summary>
        internal static string SelectedFiles {
            get {
                return ResourceManager.GetString("SelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume &amp;Properties.
        /// </summary>
        internal static string VolumeProperties {
            get {
                return ResourceManager.GetString("VolumeProperties", resourceCulture);
            }
        }
    }
}
